name: 'Deploy to AWS S3'
description: 'Deploy website to AWS S3 bucket'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  bucket-region:
    description: 'S3 bucket region'
    required: false
    default: 'us-east-1' #I don't think this is the region I've used
  dist-folder:
    description: 'Folder to deploy'
    required: true
outputs:
  success:
      website-url:
      description: 'URL of the deployed website'
runs:
  using: 'node16'
  main: 'main.js'